### ISSUE TITLE
Adopt layout from https://github.com/fulldecent/swift5-module-template

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/FDSoundActivatedRecorder#27]
A modern project layout for Swift modules is defined at https://github.com/fulldecent/swift5-module-template

# Work plan

- [ ] Study best practices at link above
- [ ] Apply the "Recipe" from the Swift 5 Module Template to this project
- [ ] Ensure that PR does not change the current development team

# Follow-on work

- [ ] Make a minor version feature release with this updated project

**Comment by fulldecent** [comment]
Fixed in 2f6d2422ccd705c2b1eea0c7ef385b9732887d4e
